/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frame.java
 *
 * Created on 15/11/2013, 20:46:22
 */

package br.org.baixadou;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingWorker;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author pedro
 */
public class frame extends javax.swing.JFrame {

	/** Creates new form frame */
	public frame() {
		initComponents();
		ajeitaForm();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBtnLocalSalvar;
	private javax.swing.JButton jBtnBaixarDou;
	private javax.swing.JButton jBtn3;

	private javax.swing.JCheckBox jChkTodas;
	private javax.swing.JCheckBox jChkSecao1;
	private javax.swing.JCheckBox jChkSecao2;
	private javax.swing.JCheckBox jChkSecao4;
	private javax.swing.JCheckBox jChkEdExtra;

	private static javax.swing.JLabel jLblFormatoData;
	private static javax.swing.JLabel jLblInfBaixandoDou;

	private JPanel jPanelTermo;
	private javax.swing.JPanel jPanelData;
	private javax.swing.JPanel jPanelSecoes;
	private javax.swing.JPanel jPanelOndeSalvar;
	private static javax.swing.JTabbedPane jTbpOpcoesBusca;

	private javax.swing.JLabel jLbllDataDou;
	private javax.swing.JTextField jTxtDataDoDou;

	private javax.swing.JLabel jLbllTermoBuscaDou;
	private javax.swing.JTextField jTxtTermoBuscaEmDou;
	private javax.swing.JCheckBox jChkTermo;

	private javax.swing.JLabel jLbllDataIni;
	private javax.swing.JTextField jTxtDataIni;

	private javax.swing.JLabel jLbllDataFim;
	private javax.swing.JTextField jTxtDataFim;

	private static javax.swing.JTextField jTxtCaminhoDiretorio;

	private static javax.swing.JCheckBox jChkMntArqBaixados;
	private javax.swing.JProgressBar jProgressBar1;
	
	private static boolean buscaTextual = false;

	public static javax.swing.JLabel getjLblInfBaixandoDou() {
		return jLblInfBaixandoDou;
	}

	public static javax.swing.JLabel getjLblFormatoData() {
		return jLblFormatoData;
	}

	public static javax.swing.JCheckBox getjChkMntArqBaixados() {
		return jChkMntArqBaixados;
	}

	public static javax.swing.JTextField getjTxtCaminhoDiretorio() {
		return jTxtCaminhoDiretorio;
	}
	
	jBtnBaixarDouSwingWorker jBtnBaixarDouWorker;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initPainelOndeSalvar() {
		jPanelOndeSalvar = new javax.swing.JPanel();

		jPanelOndeSalvar.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Onde Salvar:"));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanelOndeSalvar);
		jPanelOndeSalvar.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jTxtCaminhoDiretorio,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												304,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												37, Short.MAX_VALUE)
										.addComponent(
												jBtnLocalSalvar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jBtnLocalSalvar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																21,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTxtCaminhoDiretorio,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}

	private void initPanelSecoes() {
		jPanelSecoes = new javax.swing.JPanel();

		jPanelSecoes.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Seção:"));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanelSecoes);
		jPanelSecoes.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jChkTodas)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jChkSecao1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jChkSecao2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jChkSecao4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jChkEdExtra)
										.addContainerGap(79, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jChkTodas)
														.addComponent(
																jChkSecao1)
														.addComponent(
																jChkSecao2)
														.addComponent(
																jChkSecao4)
														.addComponent(
																jChkEdExtra))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}

	private void initPanelData() {
		jPanelData = new javax.swing.JPanel();

		// jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros:"));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanelData);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(36)
					.addComponent(jLbllDataDou)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jTxtDataDoDou, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jLblFormatoData)
					.addContainerGap(257, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTxtDataDoDou, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLbllDataDou)
						.addComponent(jLblFormatoData))
					.addContainerGap(23, Short.MAX_VALUE))
		);
		jPanelData.setLayout(jPanel1Layout);

	}

	private void initPanelTermo(){
		jPanelTermo = new JPanel();
				
		jPanelTermo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5,
				5, 5));		
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanelTermo);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLbllTermoBuscaDou)
						.addComponent(jLbllDataIni))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jTxtTermoBuscaEmDou, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
							.addGap(13))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jTxtDataIni)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addComponent(jLbllDataFim)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(jTxtDataFim, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
					.addGap(104))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTxtTermoBuscaEmDou, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLbllTermoBuscaDou))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLbllDataFim)
						.addComponent(jTxtDataFim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLbllDataIni)
						.addComponent(jTxtDataIni, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
		);
		jPanelTermo.setLayout(jPanel1Layout);
		
	}

	private void initContentPane() {
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());

		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE)
				.addComponent(jTbpOpcoesBusca,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				// .addComponent(jPanelData,
				// javax.swing.GroupLayout.DEFAULT_SIZE,
				// javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanelSecoes,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanelOndeSalvar,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLblInfBaixandoDou)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jChkMntArqBaixados))
												.addComponent(
														jBtnBaixarDou,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														380, Short.MAX_VALUE)
												.addComponent(
														jBtn3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														380, Short.MAX_VALUE))
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jProgressBar1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										380, Short.MAX_VALUE).addContainerGap())
		// .addGap(400, 400, Short.MAX_VALUE)
		);

		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 266, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jTbpOpcoesBusca,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								// .addPreferredGap(
								// javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								// .addComponent(jPanelData,
								// javax.swing.GroupLayout.PREFERRED_SIZE,
								// javax.swing.GroupLayout.DEFAULT_SIZE,
								// javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanelSecoes,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanelOndeSalvar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jBtnBaixarDou,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jBtn3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLblInfBaixandoDou)
												.addComponent(
														jChkMntArqBaixados))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jProgressBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLblInfBaixandoDou = new javax.swing.JLabel();
		jChkMntArqBaixados = new javax.swing.JCheckBox();
		jProgressBar1 = new javax.swing.JProgressBar();
		jBtnBaixarDou = new javax.swing.JButton();
		jBtn3 = new javax.swing.JButton();

		jTxtCaminhoDiretorio = new javax.swing.JTextField();
		jBtnLocalSalvar = new javax.swing.JButton();

		jChkTodas = new javax.swing.JCheckBox();
		jChkSecao1 = new javax.swing.JCheckBox();
		jChkSecao2 = new javax.swing.JCheckBox();
		jChkSecao4 = new javax.swing.JCheckBox();
		jChkEdExtra = new javax.swing.JCheckBox();

		jLbllDataDou = new javax.swing.JLabel();
		jTxtDataDoDou = new javax.swing.JTextField();

		jLbllTermoBuscaDou = new javax.swing.JLabel();
		jTxtTermoBuscaEmDou = new javax.swing.JTextField();

		jLbllDataIni = new javax.swing.JLabel();
		jTxtDataIni = new javax.swing.JTextField();

		jLbllDataFim = new javax.swing.JLabel();
		jTxtDataFim = new javax.swing.JTextField();

		jChkTermo = new javax.swing.JCheckBox();

		jLblFormatoData = new javax.swing.JLabel();

		jTbpOpcoesBusca = new JTabbedPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		initPainelOndeSalvar();

		jTxtCaminhoDiretorio.setEditable(false);
		// jTextField2.setText("Selecione a pasta:");
		jTxtCaminhoDiretorio
				.setText("/home/guilhermepinto/Área de Trabalho/site/");

		jBtnLocalSalvar.setText("...");
		jBtnLocalSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		initPanelSecoes();

		jChkTodas.setText("Todas");
		jChkTodas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jChkTodas.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jChkTodas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jChkSecao1.setText("Seção 1");
		jChkSecao1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jChkSecao1.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jChkSecao2.setText("Seção 2");
		jChkSecao2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jChkSecao2.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jChkSecao4.setText("Seção 3");
		jChkSecao4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jChkSecao4.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jChkEdExtra.setText("Ed. Extra");
		jChkEdExtra.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jChkEdExtra.setMargin(new java.awt.Insets(0, 0, 0, 0));

		initPanelData();

		jLbllDataDou.setText("Data do DOU:");
		jLblFormatoData.setText(" (dd/MM/aaaa)");
		jTxtDataDoDou.setText("29/12/2014");

		initPanelTermo();

		jLbllTermoBuscaDou.setText("Informe o termo:");
		jTxtTermoBuscaEmDou.setText("dataprev");
		
		jLbllDataIni.setText("Data inicial:");
		jTxtDataIni.setText("20/11");
		
		jLbllDataFim.setText("Data Final:");
		jTxtDataFim.setText("29/12");
		
		
		jTbpOpcoesBusca.addTab("Busca por data", jPanelData);
		jTbpOpcoesBusca.addTab("Busca por termo", jPanelTermo);
		jTbpOpcoesBusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(
				2, 2, 2, 2));

		initContentPane();

		jLblInfBaixandoDou.setText("Baixando DOU...");
		jChkMntArqBaixados
				.setText("Mantém arquivos baixados durante o processo");
		jBtnBaixarDou.setText("BAIXAR D.O.U ");
		jBtnBaixarDou.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnBaixarDouActionPerformed(evt);
			}
		});
		jBtn3.setText("TESTE");
		jBtn3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		pack();
		
		jBtnBaixarDouWorker = new jBtnBaixarDouSwingWorker();
	}// </editor-fold>//GEN-END:initComponents
	
	private class jBtnBaixarDouSwingWorker extends SwingWorker{
		@Override
		protected Object doInBackground() throws Exception {
			try {
				preparaFrame();
				final String DATA = jTxtDataDoDou.getText();
				boolean jn1 = false, jn2 = false, jn3 = false, jn1000 = false;
				if (jChkSecao1.isSelected())
					jn1 = true;
				if (jChkSecao2.isSelected())
					jn2 = true;
				if (jChkSecao4.isSelected())
					jn3 = true;
				if (jChkEdExtra.isSelected())
					jn1000 = true;
				if (buscaTextual == true){
					jn1 = false; jn2 = false; jn3 = false; jn1000 = false;	
					siteDOU.obtemlinksDou(jTxtTermoBuscaEmDou.getText(), jTxtDataIni.getText(), jTxtDataFim.getText(), "2014");
				}

				// faz download dos DOU selecionados
				if (jn1) {
					siteDOU.downloadDow(1, DATA);
				}
				jProgressBar1.setValue(25);
				if (jn2) {
					siteDOU.downloadDow(2, DATA);
				}
				jProgressBar1.setValue(50);
				if (jn3) {
					siteDOU.downloadDow(3, DATA);
				}
				jProgressBar1.setValue(75);
				if (jn1000) {
					siteDOU.downloadDow(1000, DATA);
				}
				jProgressBar1.setValue(100);
			} catch (Exception e) {
				e.printStackTrace();
				jProgressBar1.setValue(100);
			}
			return null;
		}

		@Override
		protected void done() {
			terminado();
		}
		
	}

	private void jBtnBaixarDouActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// checa o preenchimento
		if (verificaFrame() == false)
			return;
		
		if (SwingWorker.StateValue.STARTED.equals(jBtnBaixarDouWorker.getState())){
			jBtnBaixarDouWorker.cancel(true);
			jBtnBaixarDou.setText("BAIXAR D.O.U ");
		} else{
			jBtnBaixarDouWorker = null;
			jBtnBaixarDouWorker = new jBtnBaixarDouSwingWorker();
			jBtnBaixarDouWorker.execute();
			jBtnBaixarDou.setText("CANCELAR ");
		}
		
		
		// começa proceço:
//		new SwingWorker() {
//			@Override
//			protected Object doInBackground() throws Exception {
//				try {
//					preparaFrame();
//					final String DATA = jTxtDataDoDou.getText();
//					boolean jn1 = false, jn2 = false, jn3 = false, jn1000 = false;
//					if (jChkSecao1.isSelected())
//						jn1 = true;
//					if (jChkSecao2.isSelected())
//						jn2 = true;
//					if (jChkSecao4.isSelected())
//						jn3 = true;
//					if (jChkEdExtra.isSelected())
//						jn1000 = true;
//					if (buscaTextual == true){
//						jn1 = false; jn2 = false; jn3 = false; jn1000 = false;	
//						siteDOU.obtemlinksDou(jTxtTermoBuscaEmDou.getText(), jTxtDataIni.getText(), jTxtDataFim.getText(), "2014");
//					}
//
//					// faz download dos DOU selecionados
//					if (jn1) {
//						siteDOU.downloadDow(1, DATA);
//					}
//					jProgressBar1.setValue(25);
//					if (jn2) {
//						siteDOU.downloadDow(2, DATA);
//					}
//					jProgressBar1.setValue(50);
//					if (jn3) {
//						siteDOU.downloadDow(3, DATA);
//					}
//					jProgressBar1.setValue(75);
//					if (jn1000) {
//						siteDOU.downloadDow(1000, DATA);
//					}
//					jProgressBar1.setValue(100);
//				} catch (Exception e) {
//					e.printStackTrace();
//					jProgressBar1.setValue(100);
//				}
//				return null;
//			}
//
//			@Override
//			protected void done() {
//				terminado();
//			}
//		}.execute();
		
		
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// começa processo:
		new SwingWorker() {
			@Override
			protected Object doInBackground() throws Exception {
				try {
					preparaFrame();
					List<String> links = new ArrayList<String>();
					links.add("http://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=1&pagina=50&data=26/12/2014");
					links.add("http://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=3&pagina=153&data=24/12/2014");
					links.add("http://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=3&pagina=154&data=24/12/2014");

					//siteDOU.downloadAvulso(links);

				} catch (Exception e) {
					e.printStackTrace();
					jProgressBar1.setValue(100);
				}
				return null;
			}

			@Override
			protected void done() {
				terminado();
			}
		}.execute();
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		File f = chooseFolder();
		if (f != null)
			jTxtCaminhoDiretorio.setText(f.getAbsolutePath() + "\\");
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
		marcaTodos();
	}// GEN-LAST:event_jCheckBox1ActionPerformed

	// End of variables declaration//GEN-END:variables

	final public File chooseFolder() {
		// seleciona a pasta onde os arquivos PDF serão baixados
		File file = null;
		JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("Selecione o diretório.");
		fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fc.setMultiSelectionEnabled(false);
		if (fc.showOpenDialog(null) != JFileChooser.CANCEL_OPTION)
			file = fc.getSelectedFile();
		else
			file = null;
		return file;
	}

	private void ajeitaForm() {
		this.setLocationRelativeTo(null);
		jLblInfBaixandoDou.setVisible(false);
		jProgressBar1.setVisible(false);
	}

	private void marcaTodos() {
		if (jChkTodas.isSelected()) {
			jChkSecao1.setSelected(true);
			jChkSecao2.setSelected(true);
			jChkSecao4.setSelected(true);
			jChkEdExtra.setSelected(true);
		} else {
			jChkSecao1.setSelected(false);
			jChkSecao2.setSelected(false);
			jChkSecao4.setSelected(false);
			jChkEdExtra.setSelected(false);
		}
	}

	private void terminado() {
		jProgressBar1.setVisible(false);
		jLblInfBaixandoDou.setVisible(false);
		jTxtDataDoDou.setEditable(true);
		jPanelSecoes.setVisible(true);
		jBtnLocalSalvar.setEnabled(true);
		//jBtnBaixarDou.setVisible(true);
		jChkMntArqBaixados.setVisible(true);
		JOptionPane.showMessageDialog(rootPane, "Processo concluído!");
	}

	private void preparaFrame() {
		jProgressBar1.setValue(0);
		jProgressBar1.setVisible(true);
		jLblInfBaixandoDou.setVisible(true);
		// não queremos que o usuário clique nisso durante o processo:
		jTxtDataDoDou.setEditable(false);
		jPanelSecoes.setVisible(false);
		jBtnLocalSalvar.setEnabled(false);
		//jBtnBaixarDou.setVisible(false);
		jChkMntArqBaixados.setVisible(false);
	}

	private boolean verificaFrame() {
		if (jTxtTermoBuscaEmDou.isShowing()){
			buscaTextual = true;
			return true;
		}
		
		// verifica se a data do DOU foi informada
		if (jTxtDataDoDou.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Primeiro informe a data!");
			jTxtDataDoDou.grabFocus();
			return false;
			// verifica se pelo menos 1 caderno foi selecionado
		} else if (jChkSecao1.isSelected() == false
				&& jChkSecao2.isSelected() == false
				&& jChkSecao4.isSelected() == false
				&& jChkEdExtra.isSelected() == false) {
			JOptionPane.showMessageDialog(null,
					"Informe uma seção do DOU para baixar!");
			return false;
		} else if (jTxtCaminhoDiretorio.getText().equals("Selecione a pasta:")) {
			JOptionPane.showMessageDialog(null, "Informe a pasta de destino!");
			return false;
		} else if (jTxtTermoBuscaEmDou.isShowing()
				&& "".equals(jTxtTermoBuscaEmDou.getText().trim())) {
			JOptionPane.showMessageDialog(null, "Informe um termo para busca.");
			jTxtTermoBuscaEmDou.grabFocus();
			return false;
		} 			
		return true;
	}
}